import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SignoutButton } from "./components/SignoutButton";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import { Providers } from "./providers";
import { ThemeToggleButton } from "./components/ThemeToggleButton";
import { Navbar } from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          <div className="p-10">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
